# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"subtract": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://miluio.github.io/hello_nbdev/"

git_url = "https://github.com/miluio/hello_nbdev/tree/master/"

def custom_doc_links(name): return None
