# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['subtract']

# Cell
def subtract(a, b):
    """Subtraction applied to two numbers

    Args:
        a (numeric): number to be subtracted
        b (numeric): subtractor

    Raises:
        ValueError: Raised when inputs are not numeric
    """
    try:
        return a - b
    except:
        raise ValueError("inputs should be numeric")